
services:
  - type: web
    name: bedwars-leaderboard
    runtime: python3
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn --bind 0.0.0.0:$PORT --workers 2 --timeout 120 main:app
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: bedwars-db
          property: connectionString
      - key: SESSION_SECRET
        generateValue: true
      - key: ADMIN_PASSWORD
        value: admin123
      - key: FLASK_ENV
        value: production
    scaling:
      minInstances: 1
      maxInstances: 3

databases:
  - name: bedwars-db
    databaseName: bedwars_leaderboard
    user: bedwars_user
    plan: free
